### ISSUE TITLE
Update CSS Media Selectors

### ISSUE THREAD

**Issue by jeff-follestad** [costanza13/cool-california#35]

**Comment by costanza13** [comment]
A few things that need to be covered by this:
- When the header wraps, we need to push the main content down a bit more, otherwise they run into each other.
- When the page title/sub-header wraps, it should probably go to centered (from "space-between" to "space around"?).
- On single post, map should be un-floated and probably centered.
- Photos and maps need to wrap and center (and should have a `max-width: 100%`) on the dashboard.
- User tags ("Your Interests") wrapping is wonky.
- Body padding should shrink on smaller screens -- this could be done with a media query, or by using a relative size.
